<footer>
  <div class="container">
    <ul class="footer-list">
        <li>           
            <a href="/index.shtml"><img src="/resources/images/shilp-logo-white.png" alt="Shilp : Samruddh Sanstha" title="Shilp : Samruddh Sanstha"> </a>
            <h6>Shilp</h6>
            <p>Building Resilient Organizations! </p>
        </li>
        <li>
          <ul class="footer-link">
            <li><a href="#">SHILP Program</a></li>
            <li><a href="/cbo-diaries.shtml">CBO Diaries</a></li>
            <li><a href="#">Leadership Development</a></li>
            <li><a href="#">Institutional Building</a></li>
          </ul>
        </li>
        <li>
          <ul class="footer-link">
            <li><a href="/about.shtml">About SHILP</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">Terms & Conditions</a></li>
          </ul>
        </li>
        <li>
          <h5>Follow us on</h5>
          <ul class="social-link">
            <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
            <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
          </ul>
          <ul class="footer-link contact-info">
            <li><i class="fa fa-mobile"></i><a href="tel:00000 00000">+91 00000 00000</a></li>
            <li><i class="fa fa-envelope"></i><a href="mailto:info@shilp.com">info@shilp.com</a></li>
          </ul>
        </li>
    </ul>
      <ul class="copyright">
        <li>Copyright © 2022 <strong>SHILP.</strong> All rights reserved.</li>
        <li>Powered by <a href="https://www.sublimis.tech/" target="_blank"><strong>ePorium | Sublimis</strong></a></li>
      </ul>  
  </div>
</footer>