<!-- Header Start -->
<header class="dark">
    <div class="header-top">
        <div class="top">
            <div class="container">
                <ul class="custom-top">
                    <li>
                        <ul class="font-increament" id="sizecontroldiv">
                            <li class="decreaseFont"><a class="f-sm" href="#fontsize-1">A-</a></li>
                            <li class="resetFont"><a class="f-md" href="#fontsize0">A</a></li>
                            <li class="increaseFont"><a class="f-lg" href="#fontsize1">A+</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <label id="switch" class="switch">
                            <input type="checkbox" onchange="toggleTheme()" id="slider">
                            <span class="slider round"></span>
                        </label>
                    </li>
                </ul>
            </div>
        </div>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container">
                    <ul>
                        <li>
                            <a href="#" class="navbar-brand">
                                <img src="/resources/images/shilp-logo.png" alt="logo">
                            </a>
                        </li>
                    </ul>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="#">About SHILP</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Resource Hub</a>
                                <ul class="sub-menu-block">
                                    <li>
                                        <ul>
                                            <li><a href="">SHILP Program</a></li>
                                            <li><a href="">CBO Diaries</a></li>
                                            <li><a href="">Leadership Development </a></li>
                                            <li><a href="">Institutional Building</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    Contact
                                </a> 
                            </li>
                        </ul>
                    </div>
                    <div class="searchbar">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="fa fa-search search-icon-input"></span>
                    </div>
                </div>
            </nav>
           
        </div>   
    </div>
</header>