<!-- Header CSS and Script starts -->

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="/resources/css/bootstrap.min.css">
<link rel="stylesheet" href="/resources/css/owl.carousel.min.css">
<link rel="stylesheet" href="/resources/css/aos.css">
<link rel="stylesheet" href="/resources/css/animate.css">
<link rel="stylesheet" href="/resources/css/font-awesome.min.css">

<!-- Custom styles -->
<link  rel="stylesheet" href="/resources/css/style.css">
<link rel="stylesheet" href="/resources/css/media.css">

<!-- Fonts -->
<link rel="stylesheet" href="/resources/fonts/fontawesome-webfont.eot">
<link rel="stylesheet" href="/resources/fonts/fontawesome-webfont.svg">
<link rel="stylesheet" href="/resources/fonts/fontawesome-webfont.ttf">
<link rel="stylesheet" href="/resources/fonts/fontawesome-webfont.woff">
<link rel="stylesheet" href="/resources/fonts/fontawesome-webfont.woff2">
<link rel="stylesheet" href="/resources/fonts/FontAwesome.otf">
