<!-- Header Start -->
<header class="dark">
    <div class="header-top">
        <div class="top">
            <div class="container">
                <ul class="custom-top">
                    <li class="resp-search">
                        <a class="search" href="#">
                            <div class="input-search">
                                <em class="fa fa-search"></em>
                            </div>
                        </a>
                    </li>
                    <li>
                        <ul class="font-increament" id="sizecontroldiv">
                            <li class="decreaseFont"><a class="f-sm" href="#fontsize-1">A-</a></li>
                            <li class="resetFont active"><a class="f-md" href="#fontsize0">A</a></li>
                            <li class="increaseFont"><a class="f-lg" href="#fontsize1">A+</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <label id="switch" class="switch">
                            <input type="checkbox" onchange="toggleTheme()" id="slider">
                            <span class="slider round"></span>
                        </label>
                    </li>
                </ul>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <ul>
                    <li>
                        <a href="/index.shtml" class="navbar-brand">
                            <img src="/resources/images/shilp-logo.png" alt="Shilp : Samruddh Sanstha" title="Shilp : Samruddh Sanstha">
                        </a>
                    </li>
                </ul>
                <div class="menu" id="menu">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> -->
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="#">About SHILP</a>
                        </li>
                        <li class="nav-item nav-dropdown">
                            <a class="nav-link" href="/list-resources.shtml">Resource Hub</a>
                            <ul class="sub-menu-block">
                                <li>
                                    <ul>
                                        <li class="submenu-ship"><a href="#"><img src="/resources/images/icon/submenu-shilp-program.png" alt="SHILP Program" title="SHILP Program"><span>SHILP Program</span></a></li>
                                        <li class="submenu-diaries"><a href="/cbo-diaries.shtml"><img src="/resources/images/icon/submenu-cbo-diaries.png" alt="CBO Diaries" title="CBO Diaries"><span>CBO Diaries</span></a></li>
                                        <li class="submenu-leadership"><a href="#"><img src="/resources/images/icon/submenu-ipo-leadership.png" alt="Leadership Development" title="Leadership Development"><span>Leadership Development</span></a></li>
                                        <li class="submenu-building"><a href="#"><img src="/resources/images/icon/submenu-building.png" alt="Institutional Building" title="Institutional Building"><span>Institutional Building</span></a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Contact
                            </a> 
                        </li>
                    </ul>
                </div>
                <div class="searchbar">
                    <input type="text" class="form-control" placeholder="Search">
                    <a href="/list-resources.shtml">
                        <span class="fa fa-search search-icon-input"></span>
                    </a>
                </div>
            </div>
        </nav>
           
    </div>
</header>